dubbo:
  registry:
    protocol: zookeeper
    address: 192.168.188.128:2181
  protocol:
    port: 20881
  application:
    name: demo_provider
    qos-enable: false
  scan:
    basePackages: com.offcn.servcie.impl